services:
  app:
    build: .
    tty: true
    container_name: gomingo-flask
    user: root
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    env_file:
      - .env

  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    user: root
    container_name: gomingo-mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
