# ベースイメージを指定
FROM python:3.10

# 作業ディレクトリを設定
WORKDIR /app

# Poetryをインストール
RUN curl -sSL https://install.python-poetry.org | python3 - && \
    export PATH="/root/.local/bin:$PATH"

# Poetryの環境変数設定（仮想環境の設定を無効化）
ENV POETRY_VIRTUALENVS_CREATE=false

# 必要なファイルをコピー
COPY pyproject.toml poetry.lock ./

# Poetryで依存関係をインストール
RUN /root/.local/bin/poetry install

# Flaskアプリケーションのコードをコピー
COPY . .

# ポートを公開
EXPOSE 5000

# Flaskアプリを起動
CMD ["poetry", "run", "flask", "run", "--host=0.0.0.0"]
