services:
  app:
    build: .
    runtime: nvidia
    tty: true
    container_name: gomingo-flask
    user: root
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    env_file:
      - .env
    command: python app.py

  mysql:
    platform: linux/amd64
    image: mysql:8.0
    container_name: gomingo-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: GOMINGO
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      TZ: "Asia/Tokyo"
    restart: always
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d/my.cnf
      - ./db/data:/var/lib/mysql
    command: --authentication_policy=mysql_native_password

