services:
  app:
    build: .
    tty: true
    container_name: gomingo-flask
    user: root
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    env_file:
      - .env
    command:
      python app.py

  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: gomingo-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf

